# Generated by Django 3.0.7 on 2020-06-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='robot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='robots.Robot', verbose_name='机器人'),
        ),
    ]
