# Generated by Django 3.0.10 on 2020-10-05 03:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('pair', models.CharField(max_length=30, verbose_name='pair')),
                ('market_type', models.CharField(choices=[('spots', 'Spots'), ('margin', 'Margin'), ('linear_delivery', 'Linear delivery contract'), ('linear_perpetual', 'Linear perpetual contract'), ('inverse_delivery', 'Inverse delivery contract'), ('inverse_perpetual', 'Inverse perpetual contract')], max_length=30, verbose_name='market type')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('ping_time', models.DateTimeField(blank=True, null=True, verbose_name='ping time')),
                ('strategy_parameters', jsonfield.fields.JSONField(verbose_name='strategy parameters')),
                ('target_currency', models.CharField(blank=True, max_length=10, verbose_name='target currency')),
                ('base_currency', models.CharField(blank=True, max_length=10, verbose_name='base currency')),
                ('quote_currency', models.CharField(blank=True, max_length=10, verbose_name='quote currency')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='credentials.Credential', verbose_name='exchange credential')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='strategies.Strategy', verbose_name='strategy')),
            ],
            options={
                'verbose_name': 'robot',
                'verbose_name_plural': 'robots',
            },
        ),
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('currency', models.CharField(max_length=10, verbose_name='currency')),
                ('total_principal', models.FloatField(default=0, verbose_name='total principal')),
                ('total_balance', models.FloatField(default=0, verbose_name='total balance')),
                ('total_principal_24h_ago', models.FloatField(default=0, verbose_name='total principal 24 hours ago')),
                ('total_balance_24h_ago', models.FloatField(default=0, verbose_name='total balance 24 hours ago')),
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_record', to='robots.Robot', verbose_name='robot')),
            ],
            options={
                'verbose_name': 'asset record',
                'verbose_name_plural': 'asset records',
            },
        ),
    ]
