# Generated by Django 3.0.10 on 2020-09-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='market_type',
            field=models.CharField(choices=[('spots', 'Spots'), ('margin', 'Margin'), ('linear_delivery', 'Linear delivery contract'), ('linear_perpetual', 'Linear perpetual contract'), ('inverse_delivery', 'Inverse delivery contract'), ('inverse_perpetual', 'Inverse perpetual contract')], max_length=30, verbose_name='market type'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='pair',
            field=models.CharField(max_length=20, verbose_name='pair'),
        ),
    ]
