# Generated by Django 3.1.2 on 2020-11-02 12:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20201030_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='order_store',
            field=jsonfield.fields.JSONField(blank=True, default={'data': {}, 'updatedAt': None}, verbose_name='order store'),
        ),
        migrations.AddField(
            model_name='robot',
            name='position_store',
            field=jsonfield.fields.JSONField(blank=True, default={'data': {}, 'updatedAt': None}, verbose_name='position store'),
        ),
        migrations.AddField(
            model_name='robot',
            name='strategy_store',
            field=jsonfield.fields.JSONField(blank=True, default={'data': {}, 'updatedAt': None}, verbose_name='strategy store'),
        ),
    ]
