# Generated by Django 3.1.2 on 2020-11-02 12:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_auto_20201102_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='order_store',
            field=jsonfield.fields.JSONField(blank=True, default={'orders': [], 'updatedAt': None}, verbose_name='order store'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='position_store',
            field=jsonfield.fields.JSONField(blank=True, default={'positions': [], 'updatedAt': None}, verbose_name='position store'),
        ),
    ]
