# Generated by Django 3.1.2 on 2021-03-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_auto_20201102_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrecordsnap',
            name='total_principal',
            field=models.FloatField(verbose_name='total principal'),
        ),
    ]
