# Generated by Django 3.0.7 on 2020-06-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='enable',
            new_name='enabled',
        ),
    ]
