# Generated by Django 3.0.10 on 2020-10-05 03:23

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_zh', models.CharField(blank=True, max_length=100, verbose_name='chinese name')),
                ('logo', models.ImageField(blank=True, upload_to='exchanges/logos', verbose_name='logo')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('rank', models.SmallIntegerField(default=0, verbose_name='rank')),
            ],
            options={
                'verbose_name': 'exchange',
                'verbose_name_plural': 'exchanges',
                'ordering': ['rank', '-created_at'],
            },
        ),
    ]
