# Generated by Django 3.0.7 on 2020-07-03 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=20, verbose_name='备注')),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(max_length=50, verbose_name='API密钥'))),
                ('secret', django_cryptography.fields.encrypt(models.CharField(max_length=50, verbose_name='密钥'))),
                ('passphrase', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=30, verbose_name='密码'))),
                ('test_net', models.BooleanField(default=False, verbose_name='测试网')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='创建于')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_set', to='exchanges.Exchange', verbose_name='交易所')),
            ],
            options={
                'verbose_name': '交易所凭证',
                'verbose_name_plural': '交易所凭证',
            },
        ),
    ]
