# Generated by Django 3.0.10 on 2020-10-05 03:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('note', models.CharField(blank=True, max_length=30, verbose_name='note')),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='API Key'))),
                ('secret', django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='secret'))),
                ('passphrase', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, verbose_name='passphrase'))),
                ('test_net', models.BooleanField(default=False, verbose_name='test net')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_set', to='exchanges.Exchange', verbose_name='exchange')),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credentials',
            },
        ),
    ]
