# Generated by Django 3.0.10 on 2020-09-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credential_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='is_test_net',
        ),
        migrations.AddField(
            model_name='credential',
            name='test_net',
            field=models.BooleanField(default=False, verbose_name='test net'),
        ),
    ]
