# Generated by Django 3.0.7 on 2020-06-26 16:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_qty', models.FloatField(verbose_name='仓位数量')),
                ('entry_price', models.FloatField(verbose_name='入场价格')),
                ('exit_price', models.FloatField(verbose_name='出场价格')),
                ('filled_qty', models.FloatField(verbose_name='已开仓数量')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='创建于')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='修改于')),
                ('index', models.IntegerField(verbose_name='索引')),
            ],
            options={
                'verbose_name': '网格',
                'verbose_name_plural': '网格',
            },
        ),
    ]
