# Generated by Django 3.0.7 on 2020-06-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        ('grids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='robots.Robot', verbose_name='机器人'),
        ),
    ]
