# Generated by Django 3.0.7 on 2020-07-23 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('parameters_spec', jsonfield.fields.JSONField(blank=True, verbose_name='parameters specification')),
            ],
            options={
                'verbose_name': 'strategy template',
                'verbose_name_plural': 'strategy templates',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('parameters', jsonfield.fields.JSONField(blank=True, verbose_name='parameters')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.StrategyTemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'strategy',
                'verbose_name_plural': 'strategies',
            },
        ),
    ]
