# Generated by Django 3.1.2 on 2020-10-30 08:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='specification',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='specification'),
        ),
    ]
