# Generated by Django 3.0.7 on 2020-07-30 12:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategytemplate',
            name='parameters_spec',
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='param_spec',
            field=jsonfield.fields.JSONField(blank=True, verbose_name='parameter specification'),
        ),
    ]
