# Generated by Django 3.0.7 on 2020-08-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_auto_20200730_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategytemplate',
            old_name='param_spec',
            new_name='parameter_spec',
        ),
    ]
