# Generated by Django 3.1.2 on 2020-11-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_auto_20201030_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='brief',
            field=models.CharField(blank=True, max_length=300, verbose_name='brief'),
        ),
    ]
