# Generated by Django 3.0.7 on 2020-08-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_auto_20200821_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategytemplate',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
    ]
